### ISSUE TITLE
Add config for remote servers

### ISSUE THREAD

**Issue by faragos** [p2kmgcl/page-editor-dev-server#13]
Greetings,

Your tool looks already very nice👍.  I'm mostly working with a linux vm on my mashine, which doesn't run on localhost:8080. Would it be possible to add a configuration to where the server runs?

P.S. I wrote something similiar, but simpler than yours on my own for my development.

https://github.com/faragos/lfr-js-portlet-utils
https://github.com/faragos/lfr-js-portlet-bootstrapper

and here an example how to use it.
https://github.com/faragos/lfr-js-portlet-example

**Comment by p2kmgcl** [comment]
Hi @faragos,

I'm glad you liked it :smile:. My original idea was not spending too much time one this, but I think I can remove the hardcoded "localhost:8080" easily, let me have a look.
